= Програма перегляду курсу біткоїна : Запити зацікавлених осіб
Долгова Єлизавета,
Версія 1.0.0, 22 липня 2021 року
:toc: macro
:toc-title: Зміст
:sectnums:
:chapter-label:

<<<

[preface]
.Список змін
|===
|Дата |Версія |Опис |Автор

|22.06.2021
|1.0
|Створення документа
|Долгова Єлизавета

|===

<<<

== 1. Вступ
Даний застосунок являтиме собою просту програму, що після реєстрації надає користувачу можливість 
подивитись поточний курс біткоїна по відношенню до гривні

=== Мета
Застосунок має основною метою надати можливість продивлятись курс валюти 

===  Контекст
Перелік вимог, що описані у цьому документі, є основою технічного
завдання на розробку програми перегляду курсу біткоїна.

== 2. Короткий огляд продукту
Програма надаватиме можливість користувачу зареєструватися або увійти в аккаунт та подивитись курс біткоїна

== 3. Характеристика ділових процесів

===  Типи користувачів
Передбачає два типи користувача - зареєстрований користувач та незареєстрований.
Перший може увійти та переглянути курс валюти, другий - зареєструватися

===  Взаємодія з користувачами
Взаємодія з користувачами буде проходити за допомогою застосунку на платформі node.js.

===  Характеристика бізнес-процесу
Управління системою буде виконуватись за допомогою модерації вихідного коду програми.

== 4. Функціональність.

=== Функція реєстрації
Користувач може ввести свій імейл та пароль, щоб зареєструватися у системі

=== Функція входу
Користувач може ввести свій імейл та пароль, щоб увійти у систему

=== Функція перегляду валюти
Користувач може натиснути на кнопку перегляду поточного курсу біткоїна

== 5. Доступність.
=== Локалізація.
Інтерфейс веб-застосунку повинен бути локалізованим на українську мову.

=== Програмні платформи.
Веб-застосунок повинен коректно показуватися в усіх підтримуваних версіях node.js.

=== Інтерфейс.
Інтерфейс веб-застосунку повинен бути простим та зручним для використання

== 6. Відмовостійкість.
Система повинна мати високий рівень відмовостійкості.

== 7. Захищеність.
Дані користувачів системи не обов'язково повинні бути захищені.